language: python
python:
    - 2.5
    - 2.6
    - 2.7
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors simplejson unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - pip install -r requirements.txt --use-mirrors
script:
    - nosetests
